export default {
  // 市场
  'market-volumechange': {
    nick: '变化趋势',
    query: '/vp/market/volumechange/query',
    query1: 'C01_市场板块',
    query2: '互联网声量',
    query3: 'C01A07L01_声量变化趋势模块查询按钮',
    exp: '/vp/market/volumechange/export',
    exp3: 'C01A07L02_声量变化趋势模块导出数据按钮',
  },
  'sales-analysis': {
    nick: '销量分析',
    query: '/vp/market/sales/query',
    query1: 'C01_市场板块',
    query2: '销量分析',
    query3: 'C01A03L01销量分析模块查询按钮',
    exp: '/vp/market/sales/export',
    exp3: 'C01A03L02销量分析模块导出数据按钮',
  },
  'compete-intention': {
    nick: '意向竞争',
    query: '/vp/market/intention/query',
    query1: 'C01_市场板块',
    query2: '竞争分析',
    query3: 'C01A04L01意向竞争模块查询按钮',
    exp: '/vp/market/intention/export',
    exp3: 'C01A04L02意向竞争模块导出数据按钮',
  },
  'compete-decision': {
    nick: '决策竞争',
    query: '/vp/market/deciding/query',
    query1: 'C01_市场板块',
    query2: '竞争分析',
    query3: 'C01A08L01决策竞争模块查询按钮',
    exp: '/vp/market/deciding/export',
    exp3: 'C01A08L02决策竞争模块导出数据按钮',
  },
  'model-price': {
    nick: '车型价格及优惠分析',
    query: '/vp/market/model/query',
    query1: 'C01_市场板块',
    query2: '车型价格及优惠分析',
    query3: 'C01A05L01车型价格与优惠分析模块查询按钮',
    exp: '/vp/market/model/export',
    exp3: 'C01A05L02车型价格与优惠分析模块导出数据按钮',
  },
  'style-price': {
    nick: '车款价格及促销',
    query: '/vp/market/style/query',
    query1: 'C01_市场板块',
    query2: '价格与促销',
    query3: 'C01A06L01车款价格及促销模块查询按钮',
    exp: '/vp/market/style/export',
    exp3: 'C01A06L02车款价格及促销模块导出数据按钮',
  },

  // 品牌
  'brand-key-word': {
    nick: '品牌形象',
    query: '/vp/brand/image/query',
    query1: 'C05_品牌板块',
    query2: '品牌形象',
    query3: 'C05A02L01_品牌形象模块查询按钮',
    exp: '/vp/brand/image/export',
    exp3: 'C05A02L02_品牌形象模块导出数据按钮',
  },
  'dealer-distribution': {
    nick: '经销商分布',
    query: '/vp/brand/dealer/query',
    query1: 'C05_品牌板块',
    query2: '品牌形象',
    query3: 'C05A01L01_经销商分布模块查询按钮',
    exp: '/vp/brand/dealer/export',
    exp3: 'C05A01L02_经销商分布模块导出数据按钮',
  },
  // 产品
  'product-parameter': {
    nick: '产品参数',
    query: '/vp/product/param/query',
    query1: 'C02_产品板块',
    query2: '产品参数',
    query3: 'C02A07L01_产品参数模块查询按钮',
    exp: '/vp/product/param/export',
    exp3: 'C02A07L02_产品参数模块导出数据按钮',
  },
  'product-grade': {
    nick: '产品评分',
    query: '/vp/product/score/query',
    query1: 'C02_产品板块',
    query2: '产品评分',
    query3: 'C02A01L01产品评分模块查询按钮',
    exp: '/vp/product/score/export',
    exp3: 'C02A01L02产品评分模块导出数据按钮',
  },
  'product-image': {
    nick: '产品形象',
    query: '/vp/product/image/query',
    query1: 'C01_品牌板块',
    query2: '产品形象',
    query3: 'C02A05L01产品形象模块查询按钮',
    exp: '/vp/product/image/export',
    exp3: 'C02A05L02产品形象模块导出数据按钮',
  },
  'compete-buyandnotbuyreason': {
    nick: '产品评价',
    query: '/vp/product/evaluation/query',
    query1: 'C01_品牌板块',
    query2: '产品评价',
    query3: 'C02A04L01产品评价模块查询按钮',
    exp: '/vp/product/evaluation/export',
    exp3: 'C02A04L02产品评价模块导出数据按钮',
  },

  // 受众
  'user-portrait': {
    nick: '基本信息',
    query: '/vp/audiences/info/query',
    query1: 'C03_受众板块',
    query2: '用户画像',
    query3: 'C03A01L01基础信息模块查询按钮',
    exp: '/vp/audiences/info/export',
    exp3: 'C03A01L02基本信息模块导出数据按钮',
  },
  'user-area': {
    nick: '地域',
    query: '/vp/audiences/region/query',
    query1: 'C03_受众板块',
    query2: '用户画像',
    query3: 'C03A02L01地域模块查询按钮',
    exp: '/vp/audiences/region/export',
    exp3: 'C03A02L02地域模块导出数据按钮',
  },
  'user-mobilecatalyst': {
    nick: '移动触媒',
    query: '/vp/audiences/catalyst/query',
    query1: 'C03_受众板块',
    query2: '移动触媒',
    query3: 'C03A03L01移动触媒模块查询按钮',
    exp: '/vp/audiences/catalyst/export',
    exp3: 'C03A03L02移动触媒模块导出数据按钮',
  },
  user_interest: {
    nick: '兴趣特征',
    query: '/vp/audiences/interest/query',
    query1: 'C03_受众板块',
    query2: '兴趣特征',
    query3: 'C03A07L01兴趣特征模块查询按钮',
    exp: '/vp/audiences/interest/export',
    exp3: 'C03A07L02兴趣特征模块导出数据按钮',
  },
  'user-kol-1': {
    nick: 'KOL分析',
    query: '/vp/audiences/kol/query',
    query1: 'C03_受众板块',
    query2: 'KOL分析',
    query3: 'C03A06L01KOL分析模块查询按钮',
    exp: '/vp/audiences/kol/export',
    exp3: 'C03A06L02KOL分析模块导出数据按钮',
  },
  'user-carusage': {
    nick: '购车用途',
    query: '/vp/audiences/usage/query',
    query1: 'C03_受众板块',
    query2: '购车用途',
    query3: 'C03A07L01_购车用途模块查询按钮',
    exp: '/vp/audiences/usage/export',
    exp3: 'C03A07L02_购车用途模块导出数据按钮',
  },
}
